- name: Configurar imagen base con MariaDB
  hosts: all
  become: true

  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Corregir posibles paquetes rotos
      shell: apt-get -f install -y

    - name: Instalar dependencias básicas
      apt:
        name:
          - mariadb-server
          - mariadb-client
          - python3-pymysql
        state: present
        update_cache: yes

    - name: Asegurar que MariaDB esté iniciado
      systemd:
        name: mariadb
        state: started
        enabled: true